name: deploy
description: Deploy to AWS

inputs:
  stage:
    description: The stage to deploy to
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        cache: 'pnpm'

    - run: cd aws
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash

    - run: pnpm run deploy --stage=${{ inputs.stage }}
      shell: bash
      env:
        SST_TELEMETRY_DISABLED: '1'
