name: lint
description: Lint

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 9
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: 'https://npm.pkg.github.com'
        cache: 'pnpm'

    - run: pnpm install --frozen-lockfile
      shell: bash

    - run: pnpm run lint
      shell: bash

    - run: pnpm install --frozen-lockfile
      shell: bash
      working-directory: ./aws

    - run: pnpm run typecheck
      shell: bash
      working-directory: ./aws
